Handle NaN constants
real_to_decimal prints NaN as +QNaN which made the plugin fail with
  ValueError: could not convert string to float: '+QNaN'
when the source contains __builtin_nan etc.