Handle hex values when converting to PyGcc_int
print_dec prints some 128-bit integers in hex form, which makes
use of type.min_value.constant fail with
  ValueError: invalid literal for int() with base 10: '0x8000000000000000'
when we are assuming it is in decimal form.